var ranges =
  [
    {
      "Range": "Bathurst",
      "Lat": -33.445541,
      "Long": 149.544611,
      "State": "NSW",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "6",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Bathurst"
    },
    {
      "Range": "Cessnock",
      "Lat": -32.864497,
      "Long": 151.350778,
      "State": "NSW",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "7",
      "Electronic": "Yes",
      "ET_System": "Kongsberg",
      "Clubs": "BHP, Cessnock, West Wallsend"
    },
    {
      "Range": "Gosford",
      "Lat": -33.455674,
      "Long": 151.271125,
      "State": "NSW",
      "Type": "Imperial/Metric",
      "Max_Distance": "600m",
      "Targets": "7",
      "Electronic": "Yes",
      "ET_System": "HEXTA",
      "Clubs": "Gosford District"
    },
    {
      "Range": "Goulburn",
      "Lat": -34.770336,
      "Long": 149.745637,
      "State": "NSW",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "?",
      "Electronic": "Yes",
      "ET_System": "OzScore",
      "Clubs": "Goulburn"
    },
    {
      "Range": "Hornsby",
      "Lat": -33.68712,
      "Long": 151.084996,
      "State": "NSW",
      "Type": "Metric",
      "Max_Distance": "800m",
      "Targets": "14",
      "Electronic": "Yes",
      "ET_System": "HEXTA",
      "Clubs": "Hornsby, Hornsby RSL, Manly, Roseville"
    },
    {
      "Range": "Katoomba",
      "Lat": -33.709724,
      "Long": 150.342206,
      "State": "NSW",
      "Type": "Imperial/Metric",
      "Max_Distance": "600m",
      "Targets": "4",
      "Electronic": "Yes",
      "ET_System": "Silver Mountain",
      "Clubs": "Katoomba"
    },
    {
      "Range": "Malabar",
      "Lat": -33.958751,
      "Long": 151.260098,
      "State": "NSW",
      "Type": "Metric",
      "Max_Distance": "800m",
      "Targets": "30",
      "Electronic": "Yes",
      "ET_System": "Mixed",
      "Clubs": "Concord, Holsworthy, Port Jackson, Mosman Neutral Bay, Sydney, Yorkshire"
    },
    {
      "Range": "Mudgee",
      "Lat": -32.612743,
      "Long": 149.569105,
      "State": "NSW",
      "Type": "Imperial/Metric",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Mudgee"
    },
    {
      "Range": "Spring Ridge",
      "Lat": -31.417000,
      "Long": 150.262947,
      "State": "NSW",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "6",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Spring Ridge"
    },
    {
      "Range": "Belmont",
      "Lat": -27.513646,
      "Long": 153.131253,
      "State": "QLD",
      "Type": "Imperial",
      "Max_Distance": "1000y",
      "Targets": "50",
      "Electronic": "Yes",
      "ET_System": "HEXTA",
      "Clubs": "Brisbane, Brisbane Mariners, Central, Gold Coast, Pacific, Natives, University of Qld"
    },
    {
      "Range": "Beaudesert",
      "Lat": -27.999842,
      "Long": 153.072081,
      "State": "QLD",
      "Type": "Imperial",
      "Max_Distance": "700y",
      "Targets": "?",
      "Electronic": "Yes",
      "ET_System": "OzScore",
      "Clubs": "Beaudesert"
    },
    {
      "Range": "Ipswich",
      "Lat": -27.745645,
      "Long": 152.847601,
      "State": "QLD",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "8",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Ipswich & District"
    },
    {
      "Range": "Mackay",
      "Lat": -21.182147,
      "Long": 148.992280,
      "State": "QLD",
      "Type": "Imperial/Metric",
      "Max_Distance": "800m",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Mackay"
    },
    {
      "Range": "North Arm",
      "Lat": -26.525591,
      "Long": 152.974641,
      "State": "QLD",
      "Type": "Imperial",
      "Max_Distance": "700y",
      "Targets": "?",
      "Electronic": "Yes",
      "ET_System": "Kongsberg",
      "Clubs": "North Arm"
    },
    {
      "Range": "Raglan",
      "Lat": -23.722441,
      "Long": 150.810624,
      "State": "QLD",
      "Type": "Metric",
      "Max_Distance": "1100m",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "?"
    },
    {
      "Range": "Wondai",
      "Lat": -26.334474,
      "Long": 151.889558,
      "State": "QLD",
      "Type": "Imperial",
      "Max_Distance": "1000y",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Wondai"
    },
    {
      "Range": "Bendigo",
      "Lat": -36.749823,
      "Long": 144.33791,
      "State": "VIC",
      "Type": "Imperial",
      "Max_Distance": "1000y",
      "Targets": 30,
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Bendigo, Central Victoria, Marong, South Bendigo, Victorian Police"
    },
    {
      "Range": "Lithgow",
      "Lat": -33.500826,
      "Long": 150.145599,
      "State": "NSW",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": 8,
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Lithgow"
    },
    {
      "Range": "Lyndhurst",
      "Lat": -33.681472,
      "Long": 149.048683,
      "State": "NSW",
      "Type": "Imperial",
      "Max_Distance": "700y",
      "Targets": 5,
      "Electronic": "Yes",
      "ET_System": "Kongsberg",
      "Clubs": "Lyndhurst"
    },
    {
      "Range": "Canberra",
      "Lat": -35.219593,
      "Long": 149.200678,
      "State": "ACT",
      "Type": "Metric",
      "Max_Distance": "900m",
      "Targets": 20,
      "Electronic": "Yes",
      "ET_System": "Kongsberg",
      "Clubs": "Bungendore, Canberra"
    },
    {
      "Range": "Townsville",
      "Lat": -19.359482,
      "Long": 146.496696,
      "State": "QLD",
      "Type": "Metric",
      "Max_Distance": "900m",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Townsville Marksmen"
    },
    {
      "Range": "Wingham",
      "Lat": -31.847171,
      "Long": 152.368060,
      "State": "NSW",
      "Type": "Imperial/Metric",
      "Max_Distance": "1000y",
      "Targets": "12",
      "Electronic": "Yes",
      "ET_System": "HEXTA",
      "Clubs": "Wingham"
    },
    {
      "Range": "Campbell Town",
      "Lat": -41.944709,
      "Long": 147.484742,
      "State": "TAS",
      "Type": "Imperial",
      "Max_Distance": "1200y",
      "Targets": "?",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Campbell Town"
    },
    {
      "Range": "Sandford",
      "Lat": -42.943906,
      "Long": 147.484199,
      "State": "TAS",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Sandford"
    },
    {
      "Range": "Smithton",
      "Lat": -40.852343,
      "Long": 145.142564,
      "State": "TAS",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Smithton"
    },
    {
      "Range": "Coomunga",
      "Lat": -34.673222,
      "Long": 135.731575,
      "State": "SA",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Port Lincoln"
    },
    {
      "Range": "Kapunda",
      "Lat": -34.356511,
      "Long": 138.926480,
      "State": "SA",
      "Type": "Imperial",
      "Max_Distance": "1000y",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Kapunda"
    },
    {
      "Range": "Lower Light",
      "Lat": -34.551299,
      "Long": 138.377132,
      "State": "SA",
      "Type": "Metric",
      "Max_Distance": "900m",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Cyclists Torrens Valley, Phoenix"
    },
    {
      "Range": "Monarto",
      "Lat": -35.146918,
      "Long": 139.155514,
      "State": "SA",
      "Type": "Metric",
      "Max_Distance": "1000m",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Murray Bridge"
    },
    {
      "Range": "Mount Barker",
      "Lat": -35.067965,
      "Long": 138.839298,
      "State": "SA",
      "Type": "Imperial",
      "Max_Distance": "800y",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Mount Barker"
    },
    {
      "Range": "Mount Gambier",
      "Lat": -37.951036,
      "Long": 140.800094,
      "State": "SA",
      "Type": "Imperial",
      "Max_Distance": "800y",
      "Targets": "4",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Mount Gambier"
    },
    {
      "Range": "Orroroo",
      "Lat": -32.741864,
      "Long": 138.613150,
      "State": "SA",
      "Type": "Imperial",
      "Max_Distance": "1000y",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Yanyarrie Orroroo"
    },
    {
      "Range": "Port Pirie",
      "Lat": -33.175304,
      "Long": 138.040922,
      "State": "SA",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Port Pirie"
    },
    {
      "Range": "Waikerie",
      "Lat": -34.2131667,
      "Long": 139.959000,
      "State": "SA",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Waikerie"
    },
    {
      "Range": "Wallaroo",
      "Lat": -33.939819,
      "Long": 137.602341,
      "State": "SA",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Wallaroo"
    },
    {
      "Range": "Whyalla",
      "Lat": -33.049234,
      "Long": 137.549358,
      "State": "SA",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Whyalla"
    },
    {
      "Range": "Albany",
      "Lat": -35.060454,
      "Long": 117.838481,
      "State": "WA",
      "Type": "Metric",
      "Max_Distance": "800m",
      "Targets": "20",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Albany"
    },
    {
      "Range": "Chapman Valley",
      "Lat": -28.508832,
      "Long": 114.818389,
      "State": "WA",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "3",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Chapman Valley"
    },
    {
      "Range": "Chidlow",
      "Lat": -31.891249,
      "Long": 116.263194,
      "State": "WA",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "?"
    },
    {
      "Range": "Coolilup",
      "Lat": -33.594234,
      "Long": 115.521203,
      "State": "WA",
      "Type": "Metric",
      "Max_Distance": "900m",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Busselton"
    },
    {
      "Range": "Geraldton Greenough",
      "Lat": -28.959219,
      "Long": 114.732446,
      "State": "WA",
      "Type": "Imperial/Metric",
      "Max_Distance": "900y",
      "Targets": "10",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Geraldton Greenough"
    },
    {
      "Range": "Meekatharra",
      "Lat": -26.576190,
      "Long": 118.488107,
      "State": "WA",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Meekatharra"
    },
    {
      "Range": "Wurgabup",
      "Lat": -33.568009,
      "Long": 117.915123,
      "State": "WA",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Wurgabup"
    },
    {
      "Range": "Yarloop",
      "Lat": -32.956219,
      "Long": 115.921104,
      "State": "WA",
      "Type": "Metric",
      "Max_Distance": "?",
      "Targets": "10",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Mandurah, Yarloop"
    },
    {
      "Range": "Darwin",
      "Lat": -12.396858,
      "Long": 130.943770,
      "State": "NT",
      "Type": "Metric",
      "Max_Distance": "1000m",
      "Targets": "30",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Darwin"
    },
    {
      "Range": "Alice Springs",
      "Lat": -23.776589,
      "Long": 133.822360,
      "State": "NT",
      "Type": "Metric",
      "Max_Distance": "1000m",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Central Australia"
    },
    {
      "Range": "Glenrowan",
      "Lat": -36.472660,
      "Long": 146.223441,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Wangaratta"
    },
    {
      "Range": "Horsham",
      "Lat": -36.738831,
      "Long": 142.145391,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "Yes",
      "ET_System": "HEXTA",
      "Clubs": "Horsham"
    },
    {
      "Range": "Dimboola",
      "Lat": -36.468902,
      "Long": 142.023421,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Dimboola"
    },
    {
      "Range": "Kaniva",
      "Lat": -36.392961,
      "Long": 141.248512,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Kaniva, Natimuk"
    },
    {
      "Range": "Stawell",
      "Lat": -37.080025,
      "Long": 142.804456,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Stawell"
    },
    {
      "Range": "Warracknabeal",
      "Lat": -36.228541,
      "Long": 142.411306,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Warracknabeal"
    },
    {
      "Range": "St Arnaud",
      "Lat": -36.645540,
      "Long": 143.257655,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "St Arnaud"
    },
    {
      "Range": "Nagambie",
      "Lat": -36.798395,
      "Long": 145.062803,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Nagambie"
    },
    {
      "Range": "Karramomus",
      "Lat": -36.491389,
      "Long": 145.505416,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Karramomus"
    },
    {
      "Range": "Tallangatta",
      "Lat": -36.234508,
      "Long": 147.142489,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Tallangatta"
    },
    {
      "Range": "Violet Town",
      "Lat": -36.656269,
      "Long": 145.734005,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "ECDRA"
    },
    {
      "Range": "Rosedale",
      "Lat": -38.177290,
      "Long": 146.818062,
      "State": "VIC",
      "Type": "Imperial",
      "Max_Distance": "1000y",
      "Targets": "6",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Rosedale, Warragul/Drouin"
    },
    {
      "Range": "Lang Lang",
      "Lat": -38.270122,
      "Long": 145.577144,
      "State": "VIC",
      "Type": "Imperial",
      "Max_Distance": "600y",
      "Targets": "6",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Lang Lang"
    },
    {
      "Range": "Moe",
      "Lat": -38.194688,
      "Long": 146.223698,
      "State": "VIC",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "7",
      "Electronic": "Yes",
      "ET_System": "Silver Mountain",
      "Clubs": "Moe City"
    },
    {
      "Range": "Yarram",
      "Lat": -38.527924,
      "Long": 146.724257,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Yarram"
    },
    {
      "Range": "Bacchus Marsh",
      "Lat": -37.686605,
      "Long": 144.372153,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Bacchus Marsh, Ballarat East, Vic Rail"
    },
    {
      "Range": "Colac",
      "Lat": -38.329656,
      "Long": 143.560517,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Colac"
    },
    {
      "Range": "Geelong",
      "Lat": -37.993998,
      "Long": 144.328079,
      "State": "VIC",
      "Type": "Metric",
      "Max_Distance": "900m",
      "Targets": "6",
      "Electronic": "Yes",
      "ET_System": "Kongsberg",
      "Clubs": "Geelong"
    },
    {
      "Range": "Mackereth",
      "Lat": -37.844139,
      "Long": 144.558170,
      "State": "VIC",
      "Type": "Imperial",
      "Max_Distance": "800y",
      "Targets": "6",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Werribee, Victorian Police"
    },
    {
      "Range": "Port Campbell",
      "Lat": -38.620307,
      "Long": 142.973049,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Port Campbell"
    },
    {
      "Range": "Warrnambool",
      "Lat": -38.433287,
      "Long": 142.589568,
      "State": "VIC",
      "Type": "Imperial",
      "Max_Distance": "1000y",
      "Targets": "20",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Warrnambool"
    },
    {
      "Range": "Dunkeld",
      "Lat": -37.612158,
      "Long": 142.329490,
      "State": "VIC",
      "Type": "?",
      "Max_Distance": "?",
      "Targets": "?",
      "Electronic": "?",
      "ET_System": "?",
      "Clubs": "Dunkeld/Willaura"
    },
    {
      "Range": "Hamilton",
      "Lat": -37.761115,
      "Long": 142.031614,
      "State": "VIC",
      "Type": "Imperial",
      "Max_Distance": "900y",
      "Targets": "2",
      "Electronic": "Yes",
      "ET_System": "HEXTA",
      "Clubs": "Hamilton"
    },
    {
      "Range": "Grantville",
      "Lat": -38.429892,
      "Long": 145.512167,
      "State": "VIC",
      "Type": "Imperial",
      "Max_Distance": "600y",
      "Targets": "5",
      "Electronic": "No",
      "ET_System": "N/A",
      "Clubs": "Fitzroy/Caulfield, MCC"
    }
  ];
